services:
  - type: web
    name: harpia
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: harpia-db
          property: connectionString
      - key: AUTH_SECRET
        value: harpia-secret-chave-super-segura-2026-xk9m2p
      - key: NEXTAUTH_URL
        sync: false
        value: https://harpia.onrender.com
      - key: AUTH_TRUST_HOST
        value: "true"
      - key: NODE_ENV
        value: production
  - type: pgsql
    name: harpia-db
    plan: free
    databaseName: harpia
